# Generated by Django 3.2 on 2021-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_fingers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='assinged_input',
            field=models.TextField(null=True),
        ),
    ]
