# Generated by Django 3.2 on 2021-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_input', models.TextField()),
            ],
            options={
                'permissions': [('can_play_game', 'Can play the game')],
            },
        ),
    ]
